# Project Information
site_name: SkYe's Wiki
site_description: SkYe's Wiki
site_author: SkYe
site_url: https://wiki.mrskye.cn/
remote_branch: gh-pages
remote_name: origin
google_analytics: ['UA-36723568-3', 'wiki.mrskye.cn']

# context
nav:
  - Pwn:
    - 知识点&题目索引: KnowExam/Know&Exam.md
    - 栈溢出:
      - 劫持fini_array: stackoverflow/hijack_fini_array_ROP.md
    - 格式化字符串:
      - 格式化字符串漏洞利用: fmtstr/fmtstr_exploit.md
      - 格式化字符串漏洞例子: fmtstr/fmtstr_example.md
      - 格式化字符串盲打: fmtstr/Bilnd_Pwn.md
    - Glibc堆相关:
      - 堆介绍: glibc-heap/Introduction_heap.md
      - 堆相关数据结构: glibc-heap/heap_structure.md
      - 深入理解堆的实现: 
        - 堆基础操作: glibc-heap/depth-Understanding-Ptmalloc2/basic.md
        - 内存块申请操作: glibc-heap/depth-Understanding-Ptmalloc2/malloc.md
        - 内存块释放操作: glibc-heap/depth-Understanding-Ptmalloc2/free.md
      - 堆基础Off-By-One: glibc-heap/off_by_one.md
      - Chunk Extend and Overlapping: glibc-heap/extend&overlapping.md
    - 链接器:
      - 静态链接程序利用: linker/statically_linked.md
    - About: index.md
#file 
docs:
    CNAME
    about.md

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'blue'
    accent: 'red'
  icon:
    logo: 'material/book'
  features:
    - tabs
    - instant
  font:
    text: 'Noto Sans'
    code: 'Source Code Pro'

# Repository
repo_name: 'skyedai910/wiki.mrskye.cn'
repo_url: 'https://github.com/skyedai910/wiki.mrskye.cn'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2020 SkYe'

# Customization
extra:
  search:
    language: 'zh'
  disqus: 'SkYe'
  copyright: 'CC BY-NC-SA 4.0'
extra_javascript:
  - 'https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js'
  - '_static/js/extra.js'
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css'
 

