# Project Information
site_name: SkYe's Wiki
site_description: SkYe's Wiki
site_author: SkYe
site_url: https://wiki.mrskye.cn/
remote_branch: gh-pages
remote_name: origin
google_analytics: ['UA-36723568-3', 'wiki.mrskye.cn']

# context
nav:
  - Home: index.md
  - Pwn:
    - 知识点&题目索引: KnowExam/Know&Exam.md
    - 格式化字符串:
      - 格式化字符串漏洞利用: fmtstr/fmtstr_exploit.md
      - 格式化字符串漏洞例子: fmtstr/fmtstr_example.md
    - 链接器:
      - 静态链接程序利用: linker/statically_linked.md

#file 
docs:
    CNAME
    about.md

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'blue'
    accent: 'red'
  icon:
    logo: 'material/book'
  features:
    - tabs
    - instant
  font:
    text: 'Noto Sans'
    code: 'Source Code Pro'

# Repository
repo_name: 'skyedai910/wiki.mrskye.cn'
repo_url: 'https://github.com/skyedai910/wiki.mrskye.cn'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2020 SkYe'

# Customization
extra:
  search:
    language: 'zh'
  disqus: 'SkYe'
  copyright: 'CC BY-NC-SA 4.0'
extra_javascript:
  - 'https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js'
  - '_static/js/extra.js'
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css'
 

